export enum ShipmentErrorEnum {
    shipper_date_error = "shipper_date_error",
    shipper_zipcode_mismatch_error = "shipper_zipcode_mismatch_error",
    shipper_additional_services_error = "shipper_additional_services_error",
    shipper_street_error = "shipper_street_error",
    shipper_city_error = "shipper_city_error",
    shipper_state_error = "shipper_state_error",
    shipper_zipcode_error = "shipper_zipcode_error",
    shipper_by_error = "shipper_by_error",
    shipper_first_name_error = "shipper_first_name_error",
    shipper_last_name_error = "shipper_last_name_error",
    shipper_email_error = "shipper_email_error",
    shipper_phone_number_error = "shipper_phone_number_error",
    shipper_company_name_error = "shipper_company_name_error",
    receiver_additional_services_error = "receiver_additional_services_error",
    receiver_street_error = "receiver_street_error",
    receiver_city_error = "receiver_city_error",
    receiver_state_error = "receiver_state_error",
    receiver_zipcode_error = "receiver_zipcode_error",
    receiver_zipcode_mismatch_error = "receiver_zipcode_mismatch_error",
    receiver_by_error = "receiver_by_error",
    receiver_first_name_error = "receiver_first_name_error",
    receiver_last_name_error = "receiver_last_name_error",
    receiver_email_error = "receiver_email_error",
    receiver_phone_number_error = "receiver_phone_number_error",
    receiver_company_name_error = "receiver_company_name_error",
}